---
- name: Deploy Traefik Reverse Proxy
  hosts: localhost
  #become: true
  #gather_facts: false
  vars_files:
    - "../secrets/secrets.yml"

#  roles:
#    - role: traefik

  connection: local

  roles:
    - traefik
