---
- name: Deploy CrowdSec + Traefik Bouncer
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - "{{ lookup('ansible.builtin.first_found', {'files': ['secrets.yml', 'secrets.yaml'], 'paths': [playbook_dir ~ '/../secrets']}) }}"

  roles:
    - crowdsec
